services:
  s-ui:
    image: alireza7/s-ui:latest
    container_name: s-ui
    hostname: s-ui
    restart: unless-stopped
    tty: true
    ports:
      - "443:443/tcp"
      - "443:443/udp"
      - "2095:2095/tcp"
      - "2096:2096/tcp"
    volumes:
      - ./s-ui/db:/app/db
      - ./s-ui/cert:/app/cert
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "1"

