services:
  s-ui:
    image: alireza7/s-ui:latest
    container_name: s-ui
    hostname: s-ui
    restart: unless-stopped
    tty: true
    network_mode: host
    volumes:
      - ./s-ui/db:/app/db
      - ./s-ui/cert:/app/cert
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
