# 监听地址和端口
listen: :8443

# 认证配置 (单用户)
auth:
  type: password
  password: "kydby-t3kuhs-agegRop"

# TLS 配置
tls:
  cert: "/etc/letsencrypt/live/kyson.store/fullchain.pem"
  key: "/etc/letsencrypt/live/kyson.store/privkey.pem"

quic:
  initStreamReceiveWindow: 8388608
  maxStreamReceiveWindow: 8388608
  initConnReceiveWindow: 20971520
  maxConnReceiveWindow: 20971520
  maxIdleTimeout: 30s
  maxIncomingStreams: 1024
  disablePathMTUDiscovery: false

# 日志配置
log:
  level: debug
  format: text
  output: "/var/log/hysteria/hysteria.log"

