events {
    worker_connections 1024;
}

http {
    server {
        listen 80;
        server_name kyson.site;

        # Certbot webroot 验证
        location /.well-known/acme-challenge/ {
            root /var/www/html;
        }

        # 其他请求返回 404
        location / {
            root /var/www/html;
            index index.html;
        }
    }
}
