server {
    listen 80;
    server_name kyson.store; # 替换为你的域名

    # 将其他所有 HTTP 请求重定向到 HTTPS
    location / {
        return 301 https://$host$request_uri;
    }
}

server {
    listen 443 ssl;
    server_name kyson.store; # 替换为你的域名

    ssl_certificate /etc/letsencrypt/live/kyson.store/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/kyson.store/privkey.pem;
    ssl_protocols TLSv1.2 TLSv1.3; # 推荐的 TLS 协议
    ssl_ciphers 'TLS_AES_128_GCM_SHA256:TLS_AES_256_GCM_SHA384:TLS_CHACHA20_POLY1305_SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384'; # 推荐的加密套件
    ssl_prefer_server_ciphers off;
    ssl_session_cache shared:SSL:10m;
    ssl_session_timeout 1d;
    ssl_session_tickets off;

    # 反向代理到 V2Ray
    location / {  # 使用一个路径来区分
        root /data/www;  # 容器内的路径，与 docker-compose.yml 中的映射对应
        index index.html index.htm; # 可选：指定默认首页
    }
}


